elections/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('polls.urls', namespace='polls')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url
from . import views
from django.views.generic.base import TemplateView

class IndexView(TemplateView):
    template_name = 'index.html'

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^polls/', views.index, name='index'),
    url(r'^verify', views.verify, name='verify'),
    url(r'^poll', views.poll, name='poll'),
    url(r'^register', views.register, name='register'),
    url(r'^registered', views.registered, name='registered'),
    url(r'^(?P<question_id>[0-9]+)/$',
        views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$',
        views.results, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$',
        views.vote, name='vote'),
]

polls/models.py
from django.conf import settings
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=255)
    pub_date = models.DateTimeField()
    slug = models.SlugField(blank=True)
    next_question = models.ForeignKey('self', null=True)

    def __str__(self):
        return self.question_text

    @property
    def name(self):
        return self.question_text

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Question, self).save(*args, **kwargs)

class Choice(models.Model):
    choice_text = models.CharField(max_length=255)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.question

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date < now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    username = models.URLField(blank=True)
    address = models.TextField()

    def __str__(self):
        return self.user.username

polls/forms.py
from django import forms
from django.contrib.auth.models import User
from polls.models import Question, Choice, UserProfile



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')


class UserProfileForm(forms.ModelForm):
    username = forms.CharField()
    address = forms.CharField()

    #def clean_email()
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'address',
        )

polls/views.py
from django.shortcuts import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from .models import Question, Choice, Poll, UserProfile
from .forms import UserForm, UserProfileForm
from django.views import generic


def index(request):
    context = {'questions': Question.objects.all()}
    return render(request, 'polls/index.html', context)

def poll(request):
    context = {'questions': Question.objects.all()}
    return render(request, 'polls/poll.html', context)

@login_required
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except:
         return render(request, 'polls/detail.html', {
        'question': question,
        'error_message': "You didn't select a choice."})
    else:
        selected_choice.votes += 1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

@login_required
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def verify(request):
    form = UserForm(request.POST or None)
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('polls:poll'))
            else:
                return HttpResponse('Your Registration account is disabled.')
        else:
            print('Invalid login details: {0}, {1}'.format(username, password))
            return HttpResponse('Invalid login details supplied.<br/>Details given: <br/>' +
                                '<p style="text-indent: 25px;">Username: ' + username + '</p>' +
                                '<p style="text-indent: 25px;">Password: ' + password + '</p>')

    else:
        return render(request, 'polls/verify.html', {'form': form})

def register(request):
    form = UserProfileForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            user = form.save(False)
            user.is_active = False
            user.save()

            UserProfile.objects.create(
                user=user,
                address=form.cleaned_data['address'],
                username=form.cleaned_data['username']
            )
            return HttpResponse('Thanks for Registering. Please expect your PIN in to be delivered in 7-10 business days.')
        #else:
         #   return render(request, 'polls/register.html', {'form': form})
           ## return HttpResponseRedirect(reverse, ('polls:registered'))
    else:
      ##  return render(request, 'polls/register.html', {'form': form})
     return render(request, 'polls/register.html', {'form': form})

def registered(request):
    context = {}
    return render(request, 'polls/registered.html', context)


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Office of the Philadelphia City Commissioners{% endblock %}</title>
    <!DOCTYPE html>
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootsrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="css" type="text/css" href="{% static 'images/style.css' %}"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />




</head>
<body>
<header class="masthead">
  <div class="container">
  <div class="row">
    <div class="col-sm-6">
      <h1><a href="#" title="scroll down for your viewing pleasure">Office of the City Commissioners</a><p class="lead">Philadelphia, PA</p></h1>
    </div>
    <div class="col-sm-6">
      <div class="pull-right hidden-sm">
        {% if user.is_authenticated %}
        <ul><i class="glyphicon glyphicon-log-out"></i><a href="{% url 'polls:index' %}"> End Session</a></ul>
        {% endif %}
      </div>
    </div>
  </div>
  </div>
</header>


<!-- Begin Navbar -->
<div id="nav">
  <div class="navbar navbar-default navbar-static">
    <div class="container">
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="glyphicon glyphicon-bar"></span>
        <span class="glyphicon glyphicon-bar"></span>
        <span class="glyphicon glyphicon-bar"></span>
      </a>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'polls:index' %}">Home</a></li>
          <li class="divider"></li>
        </ul>
      </div>
    </div>
  </div><!-- /.navbar -->
</div>



{% block body %}
{% endblock %}

</body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block body %}

    <div id="main">
        <div id="content">
        <section>
            <div class="container">
    {% if user.is_authenticated %}
        <h1>{{ question.question_text }}</h1>
                {% if error_message %} <p><strong>{{error_message}}</strong></p> {% endif %}

         <ul>Select one option:</ul>

        <form action = "{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value= "{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}"> {{ choice.choice_text }}</label><br />
        {% endfor %}
            <input type="submit" value="vote" />
        </form>

    {% endif %}
            </div>
        </section>


{% endblock %}

polls/templates/polls/form-template.html
<!DOCTYPE html>
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>

{% endfor %}

polls/templates/polls/index.html
<!DOCTYPE html>
{% extends 'polls/base.html'%}
{% load staticfiles %}
{% block title %}Register{% endblock %}

{% block body %}
<div id="main">
    <div id="content">
        <section>
            <div class="container">
                <h1>General Election - November 7, 2017</h1>
                <p>Welcome to the new Philadelphia voting platform. We are proud to be the first metropolitan city to offer an electronic voting option beginning just this year. To ensure the security and validity of your vote, a personalized 8 digit PIN is required. This PIN was mailed to your voter registration address at the time of your electronic voting request. If you do not have a personalized PIN, you can request it on the City Commissoner's website by October 10, 2017. In person registration is still active. Please visit <a href="https://www.philadelphiavotes.com/index.php?option=com_voterapp&tmpl=component">Find Your Polling Place</a> webpage to locate your polling site. If you are not registered to vote in Pennsylvania, please follow the link to register below.</p>
                <p>
                <li><a href="{% url 'polls:verify' %}"> <strong> Vote Today | PIN Required </strong></a></li>
                <li><a href="{% url 'polls:register' %}"> <strong> No PIN? Sign up now! </strong></a></li>
                </p>
            </div>
                <div>
                    <p>
            <a href="https://www.pavoterservices.pa.gov/Pages/VoterRegistrationApplication.aspx">
                    <img class="center-block" src="{% static 'images/vote.png' %}" alt="Picture of Philly Votes"/></a>
                    </p>
           <br>
	    </div>

{% endblock %}

polls/templates/polls/poll.html
{% extends 'polls/base.html' %}
{% block body %}
<div id="main">
    <div id="content">
        <section>
            <div class="container">
                {% if user.is_authenticated %}
                <h1> Pennsylvania Registered User: {{user.username}}</h1>{% endif %}
                <ul>For each category, select the candidate of your choice.</ul>
                <a>{% if questions %}
                    <ul>
                        {% for question in questions %}
                        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <p>No polls are available.</p>
                </a>
            </div>


            {% endif %}
            {% endblock %}

polls/templates/polls/register.html
{% extends 'polls/base.html' %}
{% block body %}

<div id="main">
    <div id="content">
        <section>
            <div class="container">
                <h1>Online Registration PIN retrieval</h1>
                <ul>Notice: you must be a Pennsylvania registered voter in order to receive a pin. If you are not registered, please visit <a href="https://www.pavoterservices.pa.gov/Pages/VoterRegistrationApplication.aspx"> PA Voter's Registration Webpage </a> </ul>
	<form method="POST" >
		{% csrf_token %}
		{{ form.as_p }}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}

		<input type="submit" name="submit" value="Submit">
		<input type="hidden" name="next" value="{{ next }}">
        <input type="hidden" name="next" value="{{ next }}">
	</form>
            </div>
        </section>

{% endblock %}

polls/templates/polls/registered.html
<!DOCTYPE html>
{% extends 'polls/base.html' %}
{% block body %}
<div id="main">
    <div id="content">
        <section>
            <div class="container">

    <title>Success!</title>

    <ul>Thank you for Registering for the Online Voting System! Expect your PIN to be delivered in 7-10 business days</ul>

</div>
        </section>
 {% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% block body %}


<div id="main">
    <div id="content">
        <section>
            <div class="container">
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

{% if question.next_question %}
    <a href="{% url 'polls:detail' question.next_question.id %}">Next Question</a>
{% else %}
    <h2>Questions complete. Thank you for voting!</h2>
{% endif %}
            </div>
        </section>
{% endblock %}

polls/templates/polls/verify.html
{% extends 'polls/base.html' %}
{% block body %}

<div id="main">
    <div id="content">
        <section>
            <div class="container">
                <h1>Verify Pennsylvania Registered User</h1>
	<form method="POST" >
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" name="submit" value="Login">
		<input type="hidden" name="next" value="{{ next }}">
	</form>
            </div>
        </section>

{% endblock %}